version: 2.5.1

networks:
  mongo-compose-network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    name: "MariaDB-Data"
  couchdb_data:
    driver: local
    name: "CouchDB-Data"
  mongodb_data:
    driver: local
    name: "MongoDB-Data"

services:
  # MariaDB Service
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: on-failure:3
    ports:
      - ${MARIADB_PORT}:3306
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file: env/mariadb.${RUN_ENV}.env
    healthcheck:
        test: mysqladmin ping -h 127.0.0.1 -u $$MARIADB_USER --password=$$MARIADB_PASSWORD --silent

  # OPA Service
  opa_bundle_server:
    image: nginx:1.21-alpine
    container_name: opa_bundle_server
    restart: on-failure:3
    ports:
      - ${OPA_BUNDLE_SERVER_PORT}:80
    volumes:
      - ./data/opa/bundles:/usr/share/nginx/html/

  opa:
    # image: openpolicyagent/opa:0.40.0-rootless
    image: openpolicyagent/opa:0.40.0-rootless
    container_name: opa
    restart: on-failure:3
    ports:
      - ${OPA_PORT}:8181
    command:
      - "run"
      - "--server"
      - "--log-format=json-pretty"
      - "--set=decision_logs.console=true"
      - "--set=services.nginx.url=http://opa_bundle_server"
      - "--set=bundles.nginx.service=nginx"
      - "--set=bundles.nginx.resource=bundle.tar.gz"
      - "--set=bundles.nginx.polling.min_delay_seconds=10"
      - "--set=bundles.nginx.polling.max_delay_seconds=30"
    depends_on:
      - opa_bundle_server

  # OAuth  Service: KeyCloak
  keycloak: 
    image: quay.io/keycloak/keycloak:18.0.0
    container_name: keycloak
    restart: on-failure:3
    ports:
      - ${KEYCLOAK_PORT}:8080
    volumes:
      - ./data/keycloak/realm-exports:/opt/keycloak/data/import
    env_file: env/keycloak.${RUN_ENV}.env
    command:
      #- --verbose
      - start-dev --import-realm
      # - start-dev
    depends_on: 
      - mariadb

  # Backend
  ## NoSQL Database
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: on-failure:3
    volumes:
      - mongodb_data:/data/db
      - mongodb_data:/data/configdb
      - ./data/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    networks: 
      - mongo-compose-network
    env_file: env/mongodb.${RUN_ENV}.env
  ## NoSQL DBMS
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - ${MONGODB_EXPRESS_PORT}:${MONGODB_EXPRESS_PORT}
    networks: 
      - mongo-compose-network
    env_file: env/mongo-express.${RUN_ENV}.env
    depends_on:
      - mongo
      
  # NodeJS / ExpressJS Server
  epa-backend:
    container_name: epa-backend
    build: backend/.
    image: dominicschiller/poc-epa-backend
    ports:
      - ${EPA_BACKEND_PORT}:${EPA_BACKEND_PORT}
    networks: 
      - mongo-compose-network
    restart: on-failure:3
    env_file: env/backend.${RUN_ENV}.env
    depends_on: 
      - mongo

  # Frontend: Angular / Ionic PWA
  epa-frontend:
    container_name: epa-frontend
    build: frontend/.
    image: dominicschiller/poc-epa-frontend
    ports:
      - ${EPA_FRONTEND_PORT}:80
    restart: on-failure:3
